.TH WORDCOUNT 1 "September 2026" "OS Assignment" "User Commands"
.SH NAME
wordCount \- count words in a text
.SH SYNOPSIS
.B wordCount
.RI [ file ]
.SH DESCRIPTION
The
.B wordCount
program counts the number of words in the given text.
If a file is provided, the program reads the text from the specified file.
Words are separated by whitespace characters.
.SH AUTHOR
Fatima Nadeem <fatiinadeem1@gmail.com>
