.TH MYSTRLEN 3 "September 2026" "OS Assignment" "Library Functions"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.br
.B int mystrlen(const char *str);
.SH DESCRIPTION
The
.B mystrlen
function calculates and returns the number of characters in the given string.
The null terminating character is not included in the returned length.
.SH AUTHOR
Fatima Nadeem <fatiinadeem1@gmail.com>
